services:

  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patient_laravel
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1